### ISSUE TITLE
[TaskInstanceApi.get_task_instances] airflow_client.client.exceptions.ApiTypeError: Invalid type for variable 'trigger'

### ISSUE THREAD

**Issue by dirtyValera** [apache/airflow-client-python#92]
`TaskInstanceApi.get_task_instances` fails with

`airflow_client.client.exceptions.ApiTypeError: Invalid type for variable 'trigger'. Required value type is Trigger and passed type was NoneType at ['received_data']['task_instances'][0]['trigger']
`
Code:

```
def test_task_instances(dag_id: str, dag_run_id: str):
    api_instance = TaskInstanceApi(airflow_api_client)
    task_instances = api_instance.get_task_instances(dag_id=dag_id, dag_run_id=dag_run_id)
    print(task_instances)

test_task_instances('dag-1-1692167919', 'dag-run-1-1692167924')
```

I'm successfully able to call other API methods so I believe it is not an issue of my local Airflow setup. What am I doing wrong?

Full trace:

```
Traceback (most recent call last):
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model_utils.py", line 1802, in get_allof_instances
    allof_instance = allof_class._from_openapi_data(**model_args, **constant_args)
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model_utils.py", line 63, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model/task_instance_collection_all_of.py", line 196, in _from_openapi_data
    setattr(self, var_name, var_value)
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model_utils.py", line 202, in __setattr__
    self[attr] = value
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model_utils.py", line 527, in __setitem__
    self.set_attribute(name, value)
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model_utils.py", line 174, in set_attribute
    value = validate_and_convert_types(
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model_utils.py", line 1637, in validate_and_convert_types
    input_value[index] = validate_and_convert_types(
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model_utils.py", line 1587, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model_utils.py", line 1480, in attempt_convert_item
    raise conversion_exc
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model_utils.py", line 1471, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model_utils.py", line 1391, in deserialize_model
    return model_class._new_from_openapi_data(**kw_args)
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model_utils.py", line 63, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model_utils.py", line 387, in _new_from_openapi_data
    return cls._from_openapi_data(*args, **kwargs)
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model_utils.py", line 63, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model/task_instance.py", line 277, in _from_openapi_data
    setattr(self, var_name, var_value)
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model_utils.py", line 202, in __setattr__
    self[attr] = value
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model_utils.py", line 527, in __setitem__
    self.set_attribute(name, value)
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model_utils.py", line 174, in set_attribute
    value = validate_and_convert_types(
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model_utils.py", line 1587, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model_utils.py", line 1466, in attempt_convert_item
    raise get_type_error(input_value, path_to_item, valid_classes,
airflow_client.client.exceptions.ApiTypeError: Invalid type for variable 'trigger'. Required value type is Trigger and passed type was NoneType at ['received_data']['task_instances'][0]['trigger']

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/anov/IdeaProjects/svoe/svoe_airflow/test_airflow_api.py", line 103, in <module>
    test_task_instances('dag-1-1692167919', 'dag-run-1-1692167924')
  File "/Users/anov/IdeaProjects/svoe/svoe_airflow/test_airflow_api.py", line 91, in test_task_instances
    task_instances = api_instance.get_task_instances(dag_id=dag_id, dag_run_id=dag_run_id)
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/api/task_instance_api.py", line 1541, in get_task_instances
    return self.get_task_instances_endpoint.call_with_http_info(**kwargs)
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/api_client.py", line 868, in call_with_http_info
    return self.api_client.call_api(
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/api_client.py", line 427, in call_api
    return self.__call_api(resource_path, method,
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/api_client.py", line 242, in __call_api
    return_data = self.deserialize(
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/api_client.py", line 343, in deserialize
    deserialized_data = validate_and_convert_types(
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model_utils.py", line 1587, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model_utils.py", line 1480, in attempt_convert_item
    raise conversion_exc
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model_utils.py", line 1471, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model_utils.py", line 1391, in deserialize_model
    return model_class._new_from_openapi_data(**kw_args)
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model_utils.py", line 63, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model_utils.py", line 387, in _new_from_openapi_data
    return cls._from_openapi_data(*args, **kwargs)
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model_utils.py", line 63, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model/task_instance_collection.py", line 201, in _from_openapi_data
    composed_info = validate_get_composed_info(
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model_utils.py", line 2010, in validate_get_composed_info
    allof_instances = get_allof_instances(self, model_args, constant_args)
  File "/Users/anov/miniconda3/envs/env_py_3-10/lib/python3.10/site-packages/airflow_client/client/model_utils.py", line 1807, in get_allof_instances
    raise ApiValueError(
airflow_client.client.exceptions.ApiValueError: Invalid inputs given to generate an instance of 'TaskInstanceCollectionAllOf'. The input data was invalid for the allOf schema 'TaskInstanceCollectionAllOf' in the composed schema 'TaskInstanceCollection'. Error=Invalid type for variable 'trigger'. Required value type is Trigger and passed type was NoneType at ['received_data']['task_instances'][0]['trigger']

```

**Comment by dirtyValera** [comment]
I believe it is similar to https://github.com/apache/airflow-client-python/issues/20

Setting `_check_return_type=False` helped

**Comment by pierrejeambrun** [comment]
There was an issue with the OpenAPI spec used for the generator. This has been fixed in latest rc,  (2.7.0rc1): https://pypi.org/project/apache-airflow-client/#history

Stable 2.7.0 release containing the fix will be released shortly. You can check the dev mailing list for more information.

Closing, feel free to re-open if needed.
